/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketPulseRouteImport } from './routes/Market-Pulse'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiBondsRouteImport } from './routes/api/bonds'
import { Route as ApiFxRouteImport } from './routes/api/fx'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminArticlesRouteImport } from './routes/_authenticated/admin.articles'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as ApiNewsletterGenerateRouteImport } from './routes/api/newsletter/generate'
import { Route as AuthenticatedAdminWriteIdRouteImport } from './routes/_authenticated/admin.write.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketPulseRoute = MarketPulseRouteImport.update({
  id: '/Market-Pulse',
  path: '/Market-Pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiBondsRoute = ApiBondsRouteImport.update({
  id: '/api/bonds',
  path: '/api/bonds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFxRoute = ApiFxRouteImport.update({
  id: '/api/fx',
  path: '/api/fx',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminArticlesRoute =
  AuthenticatedAdminArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiNewsletterGenerateRoute = ApiNewsletterGenerateRouteImport.update({
  id: '/api/newsletter/generate',
  path: '/api/newsletter/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminWriteIdRoute =
  AuthenticatedAdminWriteIdRouteImport.update({
    id: '/write/$id',
    path: '/write/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Market-Pulse': typeof MarketPulseRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/bonds': typeof ApiBondsRoute
  '/api/fx': typeof ApiFxRoute
  '/api/news': typeof ApiNewsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/api/newsletter/generate': typeof ApiNewsletterGenerateRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/write/$id': typeof AuthenticatedAdminWriteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Market-Pulse': typeof MarketPulseRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/bonds': typeof ApiBondsRoute
  '/api/fx': typeof ApiFxRoute
  '/api/news': typeof ApiNewsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/api/newsletter/generate': typeof ApiNewsletterGenerateRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/write/$id': typeof AuthenticatedAdminWriteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/Market-Pulse': typeof MarketPulseRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/bonds': typeof ApiBondsRoute
  '/api/fx': typeof ApiFxRoute
  '/api/news': typeof ApiNewsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/_authenticated/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/api/newsletter/generate': typeof ApiNewsletterGenerateRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/write/$id': typeof AuthenticatedAdminWriteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Market-Pulse'
    | '/about'
    | '/auth'
    | '/categories'
    | '/sitemap.xml'
    | '/admin'
    | '/api/bonds'
    | '/api/fx'
    | '/api/news'
    | '/articles/$slug'
    | '/articles/'
    | '/admin/articles'
    | '/admin/categories'
    | '/admin/settings'
    | '/api/newsletter/generate'
    | '/admin/'
    | '/admin/write/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Market-Pulse'
    | '/about'
    | '/auth'
    | '/categories'
    | '/sitemap.xml'
    | '/api/bonds'
    | '/api/fx'
    | '/api/news'
    | '/articles/$slug'
    | '/articles'
    | '/admin/articles'
    | '/admin/categories'
    | '/admin/settings'
    | '/api/newsletter/generate'
    | '/admin'
    | '/admin/write/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/Market-Pulse'
    | '/about'
    | '/auth'
    | '/categories'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/api/bonds'
    | '/api/fx'
    | '/api/news'
    | '/articles/$slug'
    | '/articles/'
    | '/_authenticated/admin/articles'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/settings'
    | '/api/newsletter/generate'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/write/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  MarketPulseRoute: typeof MarketPulseRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiBondsRoute: typeof ApiBondsRoute
  ApiFxRoute: typeof ApiFxRoute
  ApiNewsRoute: typeof ApiNewsRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ApiNewsletterGenerateRoute: typeof ApiNewsletterGenerateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Market-Pulse': {
      id: '/Market-Pulse'
      path: '/Market-Pulse'
      fullPath: '/Market-Pulse'
      preLoaderRoute: typeof MarketPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/bonds': {
      id: '/api/bonds'
      path: '/api/bonds'
      fullPath: '/api/bonds'
      preLoaderRoute: typeof ApiBondsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fx': {
      id: '/api/fx'
      path: '/api/fx'
      fullPath: '/api/fx'
      preLoaderRoute: typeof ApiFxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/articles': {
      id: '/_authenticated/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AuthenticatedAdminArticlesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/newsletter/generate': {
      id: '/api/newsletter/generate'
      path: '/api/newsletter/generate'
      fullPath: '/api/newsletter/generate'
      preLoaderRoute: typeof ApiNewsletterGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/write/$id': {
      id: '/_authenticated/admin/write/$id'
      path: '/write/$id'
      fullPath: '/admin/write/$id'
      preLoaderRoute: typeof AuthenticatedAdminWriteIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminArticlesRoute: typeof AuthenticatedAdminArticlesRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminWriteIdRoute: typeof AuthenticatedAdminWriteIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminArticlesRoute: AuthenticatedAdminArticlesRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminWriteIdRoute: AuthenticatedAdminWriteIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  MarketPulseRoute: MarketPulseRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiBondsRoute: ApiBondsRoute,
  ApiFxRoute: ApiFxRoute,
  ApiNewsRoute: ApiNewsRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ApiNewsletterGenerateRoute: ApiNewsletterGenerateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
